#!/usr/bin/env bash
#Transfer file from local system to server
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
server="$2"
username="$3"
ssh_key="$4"
# Running the scp command
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server:~/"
