#!/usr/bin/env bash
# Configure nginx server to redirect

export string="\n\tlocation /redirect_me {\n\t\t# Redirection page\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/server_name _;/a\\ $string" /etc/nginx/sites-available/default
sudo nginx -t
sudo nginx -s reload
