#!/usr/bin/env bash
# Configuring Nginx server to contain a custom header
sudo sed -i "/location \/ {/a\\\t\t#Custom header\n\t\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
