#!/usr/bin/env bash
#!/usr/bin/env bash
# Configure nginx server to redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
yes | sudo ufw enable
cd /var/www/html || exit
sudo touch index.html
sudo sh -c 'echo "Hello World!" > index.html'
export string="\n\tlocation /redirect_me {\n\t\t# Redirection page\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/server_name _;/a\\ $string" /etc/nginx/sites-available/default
sudo mkdir -p /var/www/html/error_pages
sudo touch /var/www/html/error_pages/error_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_pages/error_404.html
sudo sed -i "/ssl_prefer_server_ciphers on;/a\\ error_page 404 /error_pages/error_404.html;" /etc/nginx/nginx.conf
sudo sed -i "/location \/ {/a\\\t\t#Custom header\n\t\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sudo nginx -t
sudo nginx -s reload
