#!/usr/bin/env bash
# Configures a server to run nginx as nginx

service nginx stop
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /var/www/html
chmod u+r /etc/nginx/nginx.conf
su - nginx -c "service nginx start"
