#!/usr/bin/env bash
# Configures a server to run nginx as nginx
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx
chmod u+r /etc/nginx/nginx.conf
su - nginx -c "service nginx start"
